---
title: "Data Matrices"
author: "Jade Shi"
date: "Winter 2019"
output:
  html_document:
    theme: spacelab
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
---

```{r}
getwd()
```

```{r}
install.packages("tidyverse")
```


```{r}
library("tidyverse")
```


```{r}
fish <- readr::read_csv("~/Desktop/class_files-master/Gaeta_etal_CLC_data.csv")
```

## Summary Functions
```{r}
names(fish)
```

```{r}
head(fish)
```

```{r}
summary(fish)
```

```{r}
glimpse(fish)
```

```{r}
str(fish)
```
## Q1 loading
```{r}
mammal <- readr::read_csv("~/Desktop/class_files-master/mammal_lifehistories_v2.csv")
```

## Dplyr:filter()

```{r}
names(fish)
```

```{r}
filter(fish, lakeid == "AL")
```



```{r}
filter(fish, length == 350 & lakeid =="FD")
```

```{r}
filter(fish, length == 167 | length == 175)
```

```{r}
filter(fish, !length == 175)
```

```{r}
filter(fish, lakeid == "DY")
```

```{r}
filter(fish, !lakeid == "AL")
```

```{r}
filter(fish,!lakeid == "AL" & !lakeid == "DY")
```

```{r}
filter(fish, scalelength >= 11)
```

```{r}
filter(fish, lakeid == "AL" & scalelength >= 2 & scalelength <=4)
```

##pipes
```{r}
fish %>% 
  filter(lakeid == "AL")
```

## select()
```{r}
fish %>%
  select(lakeid, scalelength) %>%
  filter(lakeid =="AL",
         scalelength >=2 & scalelength <=4)
```

