---
title: "Jade's section"
output: 
  html_document: 
    keep_md: yes
---

```{r}
##install.packages("tidyverse")
##install.packages("skimr")
##install.packages("RColorBrewer")
library("RColorBrewer")
library(tidyverse)
library(skimr)
```


```{r}
bee <- 
  readr::read_csv("C:/Users/JIN/Downloads/Animals-master/Jade's/bee2.csv")
bee
```

```{r}
names(bee)
```

## Renaming the colnames
```{r}
bee <- 
  bee %>% 
  dplyr::rename(
          year        = "Year",
          season      = "Season",
          state       = "State",
          totAnnualLoss = "Total Annual Loss",
          beekeepers = "Beekeepers",
          beekeepersExclusive = "Beekeepers Exclusive to State",
          colonies = "Colonies",
          coloniesExclusive =  "Colonies Exclusive to State" 
   )
```

##Is it true bees are losing?
```{r}
bee_2010<- 
  bee %>%
  filter(year =="2010/11") %>% 
  arrange(desc(totAnnualLoss))
bee_2010
```

## Top 5 states with the highest colony loss in 2010
```{r}
bee_2010 %>% 
  filter(totAnnualLoss >=0.75) %>% 
  ggplot(aes(state, totAnnualLoss, fill = state))+
  geom_col()+
  labs(title= "Top 5 States with the Highest Colony Loss in 2010")+
  theme(axis.text.x = element_text(hjust= 0.95, size=rel(0.5)))+
  theme(plot.title = element_text(size = rel(1), hjust = 0.5))+
  theme_bw()
```

##In the most recent year 2016-2017
```{r}
bee_2016<-
  bee %>% 
  filter(year =="2016/17") %>% 
  arrange(desc(totAnnualLoss))
bee_2016
```

##Top 5 states with the highest colony loss in 2016
```{r}
bee_2016 %>% 
  filter(totAnnualLoss >=0.65) %>% 
  ggplot(aes(state, totAnnualLoss, fill = state))+
  geom_col()+
  labs(title= "Top 5 States with the Highest Colony Loss in 2017")+
  theme(axis.text.x = element_text(hjust= 0.95, size=rel(0.5)))+
  theme(plot.title = element_text(size = rel(1), hjust = 0.5))
```


##Average lossage of the colony in U.S.
```{r}
average_loss<-
bee %>% 
  group_by(year) %>% 
  summarize(mean_annualLoss = mean(totAnnualLoss,na.rm = TRUE))
average_loss
```

##Average Annual loss through out the year
```{r}
average_loss %>% 
  ggplot(aes(year,mean_annualLoss,size = mean_annualLoss, color=year))+
  geom_point()+
  labs(title = "Average Colony Loss from 2010 to 2017",
       x = "Year",
       y = "Mean Annual Loss")+
  theme(axis.title = element_text(hjust = 0.95))+
  theme(axis.text.x = element_text(size= rel(1)))
```









